server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: "logfiles"
    static_configs:
      - targets:
          - localhost
        labels:
          job: app-a
          __path__: /logs/app-a.log
      - targets:
          - localhost
        labels:
          job: app-b
          __path__: /logs/app-b.log
