# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Prometheus
    orgId: 1

# list of datasources to insert/update depending
# what's available in the database
datasources:
  # <string, required> name of the datasource. Required
  - uid: prometheus
    orgId: 1
    name: Prometheus
    type: prometheus
    typeName: Prometheus
    access: proxy
    url: http://prometheus:9090
    password: ''
    user: ''
    database: ''
    basicAuth: false
    isDefault: true
    jsonData:
      exemplarTraceIdDestinations:
        - datasourceUid: tempo
          name: trace_id
      httpMethod: POST
    readOnly: false
    editable: true
  - uid: tempo
    orgId: 1
    name: Tempo
    type: tempo
    typeName: Tempo
    access: proxy
    url: http://tempo
    readOnly: false
    editable: true
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: 'prometheus'
      nodeGraph:
        enabled: true
      search:
        hide: false
      lokiSearch:
        datasourceUid: loki
      tracesToLogsV2:
        customQuery: false
        datasourceUid: loki
        filterBySpanID: false
        filterByTraceID: true
        spanEndTimeShift: 3m
        spanStartTimeShift: '-3m'
        tags:
          - key: compose_service
      tracesToMetrics:
        datasourceUid: prometheus
        queries:
          - name: Request Rate Per Min
            query: >-
              sum(rate(traces_spanmetrics_latency_count{$$__tags}[3m])*60)
              by(service, span_name)
          - name: Request Duration PR95
            query: >-
              histogram_quantile(0.95,
              sum(rate(traces_spanmetrics_latency_bucket{$$__tags}[3m])) by (le, service, span_name))
        spanEndTimeShift: 15m
        spanStartTimeShift: '-15m'
        tags:
          - key: service.name
            value: service
          - key: http.target
            value: http_target
  - uid: loki
    orgId: 1
    name: Loki
    type: loki
    typeName: Loki
    access: proxy
    url: http://loki:3100
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: (?:trace_id)=(\w+)
          name: TraceID
          url: $${__value.raw}